import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Project from "./project";
import About from "./about";
import Contact from "./contact";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio-Css",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>


        {children}
        <Project/>
        <About/>
        <Contact/>
        </body>
    </html>
  );
}
